### ISSUE TITLE
user stories analysis

### ISSUE THREAD

**Issue by amyconroy** [Team-Jag/Do-or-die-fitness-tracker#122]
why did we choose these user stories - addressing what problems? 
grace we can do this? or anyone else if they wanna hop on

**Comment by a-shmyg** [comment]
@amyconroy i had a look and tried to draft out what product problems we were solving through our user stories, feel free to change completely if it doesn't work with our current flow, just a potential draft

**Comment by amyconroy** [comment]
> @amyconroy i had a look and tried to draft out what product problems we were solving through our user stories, feel free to change completely if it doesn't work with our current flow, just a potential draft

i just got tear-y eyed you are the BEST
