### ISSUE TITLE
Architecture of the System 

### ISSUE THREAD

**Issue by amyconroy** [Team-Jag/Do-or-die-fitness-tracker#46]
System design part a : make a UML for the entire architecture (?). Ana you can decide how you want this done - do you want us to first make the UML for the subsystems and then merge that together, or are you okay making one general UML?

**Comment by amyconroy** [comment]
@a-shmyg  in architecture section do you think you could write a bit about the requirements from the assignment brief (ie the data repository, data communication, web, desktop, and the fact that its an IoT device) - should be quite easy, just need to apply to the 'essential components' to our architecture (I can help / edit after to add more !)

**Comment by a-shmyg** [comment]
Yes will flesh out the section
