### ISSUE TITLE
UML web

### ISSUE THREAD

**Issue by amyconroy** [Team-Jag/Do-or-die-fitness-tracker#52]
for system design

**Comment by Chris19138** [comment]
our methods in the UML diagram are:
pushNewProfile
pullWebProfile
pushNewChallenge
pushSelectChallenge

**Comment by amyconroy** [comment]
@Chris19138 we were originally thinking of more specific UML per subsystem, cause @a-shmyg just did a basic overview (right ana?)

**Comment by amyconroy** [comment]
> @Chris19138 we were originally thinking of more specific UML per subsystem, cause @a-shmyg just did a basic overview (right ana?)

this is for the object oriented programming btw

**Comment by a-shmyg** [comment]
yes i did a general UML for request types between communication devices, just using the request types you described @Chris19138. There are some issues (typos) with it so when I update to include the new pull_stats request I will also update Web to relflect those

**Comment by a-shmyg** [comment]
it would be worth doing a more specific Web UML to see how pages interact with each other
