### ISSUE TITLE
web user stories added to sprint gantt chart

### ISSUE THREAD

**Issue by amyconroy** [Team-Jag/Do-or-die-fitness-tracker#64]
on excel spreadsheet :)

**Comment by Chris19138** [comment]
Link:
https://uob-my.sharepoint.com/:x:/g/personal/ac16888_bristol_ac_uk/EXltfbLEnNFLrGLOGOxgZcIBiPorw6Hvw7Q5EqTrx0LpCQ?rtime=4rAqMZzq10g

**Comment by amyconroy** [comment]
thank youuuu <3

**Comment by Chris19138** [comment]
the colours are not explained, but content looks good (Y)
